version: '3.1'

services:

  hapi:
    image: "hapiproject/hapi:v6.10.1"
    container_name: APIFHIRSERVER
    ports:
      - "8980:8080"
    volumes:
      - ./fhir-configs:/data/hapi
    environment:
      SPRING_CONFIG_LOCATION: 'file:///data/hapi/irccs-application.yaml'
